### ISSUE TITLE
Error: Cannot find module 'rucaptcha-solver'

### ISSUE THREAD

**Issue by EAIvanov** [bogdan0083/rucaptcha-solver#2]
при установке и подключении выдаёт:

> internal/modules/cjs/loader.js:583
>     throw err;
>     ^
> 
> Error: Cannot find module 'rucaptcha-solver'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (/Users/GDie/Desktop/nodejs/codes/index.js:2:15)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
> 
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by TAnas0** [comment]
This package is not well maintained.
There seems that the version published in NPM is outdated from the content you see in the master branch.

Either install directly from the github repository in your `npm install` command, or try:
```javascript
var Solver = require('rucaptcha-solver/src/solver')
```

**Comment by bogdan0083** [comment]
I finally found the time to fix this bug. I'm gonna close the issue but feel free to open the new one if something doesn't work.
